name: gow_elden_cup
description: "GoW Album — a sticker-album of God of War Ragnarök bosses & favors."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/gow_bosses.json
    - assets/gow_favors.json
    - assets/images/
    - assets/images/map/
    - assets/images/loot/
    - assets/images/runes/
    - assets/images/shrines/
    - assets/images/ui/
    - assets/images/bosses/
